# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: traces.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'traces.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctraces.proto\x12\ropentelemetry\"]\n\x08\x41nyValue\x12\x14\n\x0cstring_value\x18\x01 \x01(\t\x12\x12\n\nbool_value\x18\x02 \x01(\x08\x12\x11\n\tint_value\x18\x03 \x01(\x03\x12\x14\n\x0c\x64ouble_value\x18\x04 \x01(\x01\"?\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12&\n\x05value\x18\x02 \x01(\x0b\x32\x17.opentelemetry.AnyValue\"\'\n\x06Status\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\"\xeb\x01\n\x04Span\x12\x10\n\x08trace_id\x18\x01 \x01(\x0c\x12\x0f\n\x07span_id\x18\x02 \x01(\x0c\x12\x16\n\x0eparent_span_id\x18\x04 \x01(\x0c\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x0c\n\x04kind\x18\x06 \x01(\x05\x12\x1c\n\x14start_time_unix_nano\x18\x07 \x01(\x06\x12\x1a\n\x12\x65nd_time_unix_nano\x18\x08 \x01(\x06\x12+\n\nattributes\x18\t \x03(\x0b\x32\x17.opentelemetry.KeyValue\x12%\n\x06status\x18\x0f \x01(\x0b\x32\x15.opentelemetry.Status\"0\n\nScopeSpans\x12\"\n\x05spans\x18\x02 \x03(\x0b\x32\x13.opentelemetry.Span\"7\n\x08Resource\x12+\n\nattributes\x18\x01 \x03(\x0b\x32\x17.opentelemetry.KeyValue\"j\n\rResourceSpans\x12)\n\x08resource\x18\x01 \x01(\x0b\x32\x17.opentelemetry.Resource\x12.\n\x0bscope_spans\x18\x02 \x03(\x0b\x32\x19.opentelemetry.ScopeSpans\"Q\n\x19\x45xportTraceServiceRequest\x12\x34\n\x0eresource_spans\x18\x01 \x03(\x0b\x32\x1c.opentelemetry.ResourceSpansb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'traces_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANYVALUE']._serialized_start=31
  _globals['_ANYVALUE']._serialized_end=124
  _globals['_KEYVALUE']._serialized_start=126
  _globals['_KEYVALUE']._serialized_end=189
  _globals['_STATUS']._serialized_start=191
  _globals['_STATUS']._serialized_end=230
  _globals['_SPAN']._serialized_start=233
  _globals['_SPAN']._serialized_end=468
  _globals['_SCOPESPANS']._serialized_start=470
  _globals['_SCOPESPANS']._serialized_end=518
  _globals['_RESOURCE']._serialized_start=520
  _globals['_RESOURCE']._serialized_end=575
  _globals['_RESOURCESPANS']._serialized_start=577
  _globals['_RESOURCESPANS']._serialized_end=683
  _globals['_EXPORTTRACESERVICEREQUEST']._serialized_start=685
  _globals['_EXPORTTRACESERVICEREQUEST']._serialized_end=766
# @@protoc_insertion_point(module_scope)
